"""
Form name constants for the ALE system.
These constants define the standard form names used throughout the application.
Form names should be short, readable, and suitable for URLs.
"""

# Employee-related forms
DIRECT_DEPOSIT = "DIRECT_DEPOSIT"
BACKGROUND_CHECK = "BACKGROUND_CHECK"
NEW_HIRE_INITIAL_CONTACT = "NEW_HIRE_INITIAL_CONTACT"
SFC_NEW_HIRE_INITIAL_CONTACT = "SFC_NEW_HIRE_INITIAL_CONTACT"
W4_FORM = "W4_FORM"
I9_FORM = "I9_FORM"
EMERGENCY_CONTACT = "EMERGENCY_CONTACT"
BENEFITS_ENROLLMENT = "BENEFITS_ENROLLMENT"
FINANCIALS = "FINANCIALS"
SFC_FINANCIALS = "SFC_FINANCIALS"
NEW_HIRE_PAPERWORK = "NEW_HIRE_PAPERWORK"
INTAKE_REFERRAL_FORM = "INTAKE_REFERRAL_FORM"

# Patient-related forms
PATIENT_INTAKE = "PATIENT_INTAKE"
MEDICAL_HISTORY = "MEDICAL_HISTORY"
INSURANCE_INFORMATION = "INSURANCE_INFORMATION"
CONSENT_FORMS = "CONSENT_FORMS"
ADVANCE_DIRECTIVE = "ADVANCE_DIRECTIVE"
PHARMACY_INFORMATION = "PHARMACY_INFORMATION"

# Organization-related forms
ORGANIZATION_REGISTRATION = "ORGANIZATION_REGISTRATION"
LICENSE_VERIFICATION = "LICENSE_VERIFICATION"
INSURANCE_CERTIFICATE = "INSURANCE_CERTIFICATE"
CONTRACT_AGREEMENT = "CONTRACT_AGREEMENT"

# Care-related forms
CARE_PLAN = "CARE_PLAN"
MEDICATION_LIST = "MEDICATION_LIST"
ALLERGY_INFORMATION = "ALLERGY_INFORMATION"
EMERGENCY_PROCEDURES = "EMERGENCY_PROCEDURES"

# Compliance forms
HIPAA_COMPLIANCE = "HIPAA_COMPLIANCE"
OSHA_TRAINING = "OSHA_TRAINING"
SAFETY_TRAINING = "SAFETY_TRAINING"
COMPLIANCE_ACKNOWLEDGMENT = "COMPLIANCE_ACKNOWLEDGMENT"

# Form categories for organization
EMPLOYEE_FORMS = {
    DIRECT_DEPOSIT,
    BACKGROUND_CHECK,
    NEW_HIRE_INITIAL_CONTACT,
    SFC_NEW_HIRE_INITIAL_CONTACT,
    W4_FORM,
    I9_FORM,
    EMERGENCY_CONTACT,
    BENEFITS_ENROLLMENT,
    FINANCIALS,
    SFC_FINANCIALS,
    NEW_HIRE_PAPERWORK,
    INTAKE_REFERRAL_FORM,
}

PATIENT_FORMS = {
    PATIENT_INTAKE,
    MEDICAL_HISTORY,
    INSURANCE_INFORMATION,
    CONSENT_FORMS,
    ADVANCE_DIRECTIVE,
    PHARMACY_INFORMATION,
}

ORGANIZATION_FORMS = {
    ORGANIZATION_REGISTRATION,
    LICENSE_VERIFICATION,
    INSURANCE_CERTIFICATE,
    CONTRACT_AGREEMENT,
}

CARE_FORMS = {
    CARE_PLAN,
    MEDICATION_LIST,
    ALLERGY_INFORMATION,
    EMERGENCY_PROCEDURES,
}

COMPLIANCE_FORMS = {
    HIPAA_COMPLIANCE,
    OSHA_TRAINING,
    SAFETY_TRAINING,
    COMPLIANCE_ACKNOWLEDGMENT,
}

# All form names for validation
FORM_NAMES = (
    EMPLOYEE_FORMS | 
    PATIENT_FORMS | 
    ORGANIZATION_FORMS | 
    CARE_FORMS | 
    COMPLIANCE_FORMS
)
